// One-off: fetch world-atlas, extract CHINA + JAPAN, project equirectangular, simplify,
// and bake STATIC svg paths into ../elements/country-paths.js (no runtime CDN at capture).
const fs = require('fs');
const path = require('path');

const ATLAS = 'https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-110m.json';
const TOPO  = 'https://cdn.jsdelivr.net/npm/topojson-client@3/dist/topojson-client.min.js';

const ringArea = (ring) => { let a = 0; for (let i = 0, n = ring.length; i < n; i++) { const [x1, y1] = ring[i], [x2, y2] = ring[(i + 1) % n]; a += x1 * y2 - x2 * y1; } return Math.abs(a) / 2; };
const ringMeanLat = (ring) => ring.reduce((s, p) => s + p[1], 0) / ring.length;

function bake(feat, { minArea, minLat = -90, maxLat = 90, W = 1000, PAD = 16, maxPts = 240 }) {
  const g = feat.geometry;
  const polys = g.type === 'Polygon' ? [g.coordinates] : g.coordinates;
  // keep sizeable polygons within the latitude window (drops tiny/outlying islands, e.g. Okinawa)
  const kept = polys.filter((rings) => {
    const o = rings[0];
    return ringArea(o) >= minArea && ringMeanLat(o) >= minLat && ringMeanLat(o) <= maxLat;
  });
  // bbox from KEPT polys only
  let minLon = 180, maxLon = -180, mnLat = 90, mxLat = -90;
  kept.forEach((rings) => rings[0].forEach(([lon, lat]) => {
    if (lon < minLon) minLon = lon; if (lon > maxLon) maxLon = lon;
    if (lat < mnLat) mnLat = lat; if (lat > mxLat) mxLat = lat;
  }));
  const meanLat = (mnLat + mxLat) / 2;
  const kx = Math.cos(meanLat * Math.PI / 180);
  const spanLon = (maxLon - minLon) * kx, spanLat = (mxLat - mnLat);
  const scale = (W - 2 * PAD) / spanLon;
  const H = Math.round(spanLat * scale + 2 * PAD);
  const proj = (lon, lat) => [
    +(PAD + (lon - minLon) * kx * scale).toFixed(1),
    +(PAD + (mxLat - lat) * scale).toFixed(1),
  ];
  let d = '';
  kept.forEach((rings) => {
    const outer = rings[0];
    const step = Math.max(1, Math.round(outer.length / maxPts));
    outer.forEach(([lon, lat], i) => {
      if (i % step !== 0 && i !== outer.length - 1) return;
      const [x, y] = proj(lon, lat);
      d += (i === 0 ? 'M' : 'L') + x + ' ' + y + ' ';
    });
    d += 'Z ';
  });
  return { viewBox: `0 0 ${W} ${H}`, path: d.trim(), polys: kept.length };
}

(async () => {
  const topoSrc = await (await fetch(TOPO)).text();
  const mod = { exports: {} };
  new Function('module', 'exports', topoSrc)(mod, mod.exports);
  const topojson = mod.exports;
  const topo = await (await fetch(ATLAS)).json();
  const fc = topojson.feature(topo, topo.objects.countries);
  const find = (n) => fc.features.find((f) => String(f.properties.name).toLowerCase() === n);

  const china = bake(find('china'), { minArea: 2 });
  // Japan: keep the 4 main islands (Honshu/Hokkaido/Kyushu/Shikoku), drop Okinawa (lat<29) & tiny isles
  const japan = bake(find('japan'), { minArea: 0.25, minLat: 29 });

  const out = `/* Auto-generated by _build/gen_country_paths.js — static China+Japan silhouettes (no runtime CDN). */
window.COUNTRY_PATHS = {
  china: { viewBox: "${china.viewBox}", path: "${china.path}" },
  japan: { viewBox: "${japan.viewBox}", path: "${japan.path}" }
};
`;
  const dest = path.resolve(__dirname, '..', 'elements', 'country-paths.js');
  fs.writeFileSync(dest, out);
  console.log('WROTE', dest);
  console.log('china viewBox', china.viewBox, '| polys', china.polys, '| chars', china.path.length);
  console.log('japan viewBox', japan.viewBox, '| polys', japan.polys, '| chars', japan.path.length);
})().catch((e) => { console.error(e); process.exit(1); });
