// One-off: fetch world-atlas, extract China, project equirectangular, simplify,
// and bake a STATIC svg path into ../elements/china-silhouette.js so the video has
// NO runtime CDN dependency during capture.
const fs = require('fs');
const path = require('path');

const ATLAS = 'https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-110m.json';
const TOPO  = 'https://cdn.jsdelivr.net/npm/topojson-client@3/dist/topojson-client.min.js';

(async () => {
  const topoSrc = await (await fetch(TOPO)).text();
  const mod = { exports: {} };
  new Function('module', 'exports', topoSrc)(mod, mod.exports);
  const topojson = mod.exports;
  const topo = await (await fetch(ATLAS)).json();
  const fc = topojson.feature(topo, topo.objects.countries);
  const feat = fc.features.find(f => String(f.properties.name).toLowerCase() === 'china');
  if (!feat) throw new Error('china not found');

  const g = feat.geometry;
  const polys = g.type === 'Polygon' ? [g.coordinates] : g.coordinates; // [poly][ring][pt]

  // bbox
  let minLon = 180, maxLon = -180, minLat = 90, maxLat = -90;
  polys.forEach(rings => rings[0].forEach(([lon, lat]) => {
    if (lon < minLon) minLon = lon; if (lon > maxLon) maxLon = lon;
    if (lat < minLat) minLat = lat; if (lat > maxLat) maxLat = lat;
  }));
  const meanLat = (minLat + maxLat) / 2;
  const kx = Math.cos(meanLat * Math.PI / 180);
  const W = 1000, PAD = 20;
  const spanLon = (maxLon - minLon) * kx, spanLat = (maxLat - minLat);
  const scale = (W - 2 * PAD) / spanLon;
  const H = Math.round(spanLat * scale + 2 * PAD);
  const ox = PAD, oy = PAD;
  const proj = (lon, lat) => [
    +(ox + (lon - minLon) * kx * scale).toFixed(1),
    +(oy + (maxLat - lat) * scale).toFixed(1),
  ];

  // keep only sizeable rings (drop tiny islands), simplify by skipping points
  const ringArea = ring => { let a = 0; for (let i = 0, n = ring.length; i < n; i++) { const [x1, y1] = ring[i], [x2, y2] = ring[(i + 1) % n]; a += x1 * y2 - x2 * y1; } return Math.abs(a) / 2; };
  let d = '';
  polys.forEach(rings => {
    const outer = rings[0];
    if (ringArea(outer) < 2) return;            // skip tiny islands
    const step = Math.max(1, Math.round(outer.length / 220));
    outer.forEach(([lon, lat], i) => {
      if (i % step !== 0 && i !== outer.length - 1) return;
      const [x, y] = proj(lon, lat);
      d += (i === 0 ? 'M' : 'L') + x + ' ' + y + ' ';
    });
    d += 'Z ';
  });

  const out = `/* Auto-generated by _build/gen_china_path.js — static China silhouette (no runtime CDN). */
window.CHINA_SILHOUETTE = { viewBox: "0 0 ${W} ${H}", path: "${d.trim()}" };
`;
  const dest = path.resolve(__dirname, '..', 'elements', 'china-silhouette.js');
  fs.writeFileSync(dest, out);
  console.log('WROTE', dest, '| viewBox 0 0', W, H, '| path chars', d.length);
})().catch(e => { console.error(e); process.exit(1); });
